export const ITEMS_LOADING = 'ITEMS_LOADING'
export const GET_ITEMS = 'GET_ITEMS'
export const POST_ITEMS = 'POST_ITEMS'
export const DEL_ITEMS = 'DEL_ITEMS'

export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const TOP_DESTI = 'TOP_DESTI'
export const GET_DESTI_FAIL = 'GET_DESTI_FAIL'
export const CLEAR_DESTI = 'CLEAR_DESTI'